# Generated by Django 4.0.4 on 2022-05-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower_user_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower_id',
            field=models.ManyToManyField(related_name='%(class)s_follower_id', to='v1.users'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.users'),
        ),
    ]
