# Generated by Django 4.0.4 on 2022-05-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_remove_followers_follower_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='followers',
            name='follower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_follower_id', to='v1.users'),
        ),
    ]
