# Generated by Django 4.0.4 on 2022-05-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_comments_replies_posts_comments_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_post_id', to='v1.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.users')),
            ],
        ),
    ]
