# Generated by Django 4.0.4 on 2022-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_posts_post_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
