# Generated by Django 4.0.4 on 2022-05-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_replies_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.users'),
            preserve_default=False,
        ),
    ]
