# Generated by Django 4.0.4 on 2022-05-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_replies_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
