# Generated by Django 4.0.4 on 2022-05-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='replies',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
