# Generated by Django 4.0.4 on 2022-05-25 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_comments_options_alter_followers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
