# Generated by Django 4.0.4 on 2022-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_posts_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(related_name='post_like', to='v1.users'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
