# Generated by Django 4.0.4 on 2022-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_posts_post_likes_delete_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_comment',
            field=models.ManyToManyField(related_name='post_comment', to='v1.comments'),
        ),
    ]
