# Generated by Django 4.0.4 on 2022-05-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_remove_comments_post_id_posts_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='v1.posts'),
            preserve_default=False,
        ),
    ]
