# Generated by Django 4.0.4 on 2022-05-26 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0014_rename_user_id_posts_author_posts_post_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=700)),
                ('profile_pic', models.ImageField(upload_to='profilepictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.profile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_follower_id', to='v1.profile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='v1.profile'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(related_name='post_like', to='v1.profile'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to='v1.profile'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
