# Generated by Django 4.0.4 on 2022-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_profile_alter_comments_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(height_field=96, upload_to='profilepictures', width_field=96),
        ),
    ]
