# Generated by Django 4.0.4 on 2022-05-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(height_field=96, help_text='Image dimensions 96x96', upload_to='profilepictures', width_field=96),
        ),
    ]
