# Generated by Django 4.0.4 on 2022-05-26 04:25

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=sorl.thumbnail.fields.ImageField(help_text='Image dimensions 96x96', upload_to='profilepictures'),
        ),
    ]
