# Generated by Django 4.0.4 on 2022-05-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', to='v1.profile'),
        ),
    ]
