# Generated by Django 4.0.4 on 2022-06-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_alter_followers_follower_id_alter_followers_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user_id', 'follower_id')},
        ),
    ]
